name: Build and release master

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'build/.homeychangelog.json'
      - 'build/app.json'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout
    - uses: actions/setup-node
      with:
        node-version: 16.0
    - name: Install packages
      run: npm ci && npm run prepare --if-present
    - name: Transpile with Typescript
      run: npx tsc --build tsconfig.json
    - name: Run tests
      run: npm run test
  
  echoPendingChangelog:
    name: Render pending changelog
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Check out repository code
      uses: actions/checkout
    - name: Use Node.js
      uses: actions/setup-node
      with:
        node-version: '16.0.0'
    - name: Generate standard version changelog
      run: |
        npm ci && npm run prepare --if-present
        npx standard-version --skip.commit --skip.tag
        UPDATED_VERSION=$(jq '.version' --raw-output package.json)
        npx changelog-parser | jq --raw-output --arg UPDATED_VERSION "$UPDATED_VERSION" '.versions[] | select(.version==$UPDATED_VERSION).body | if . != "" then . else "[[empty]]" end'
  
  release:
    needs: build
    name: Create release
    runs-on: ubuntu-latest
    environment:
      name: Publish
    defaults:
      run:
        shell: bash
    env:
      HOMEY_SETTINGS: ${{ secrets.HOMEY_SETTINGS }}
    steps:
    - name: Check out repository code
      uses: actions/checkout
    - name: Use Node.js
      uses: actions/setup-node
      with:
        node-version: '16.0.0'
    - name: Setup credentials
      run: |
        set -ex
        mkdir -p $HOME/.athom-cli
        printenv HOMEY_SETTINGS > $HOME/.athom-cli/settings.json
    - name: Install packages
      run: |
        set -ex
        npm ci
        npm run prepare --if-present
    - name: Tag release, bump Homey versioning, push to Github and deploy to Homey App store
      run: |
        set -e

        git config --local user.name "Github Actions"
        git config --local user.email "github-actions@example.com"

        git pull origin master

        npx standard-version

        UPDATED_VERSION=$(jq '.version' --raw-output package.json)
        CHANGE_NOTES=$(npx changelog-parser | jq --raw-output --arg UPDATED_VERSION "$UPDATED_VERSION" '.versions[] | select(.version==$UPDATED_VERSION).parsed._ | map(.[:-10]) | join(", ") | if . != "" then . else "General improvements" end')

        cp resources/app.json resources/app.json.bak
        jq --arg UPDATED_VERSION "$UPDATED_VERSION" '.version = $UPDATED_VERSION' resources/app.json.bak > resources/app.json
        rm resources/app.json.bak

        cp resources/.homeychangelog.json resources/.homeychangelog.json.bak
        jq --arg UPDATED_VERSION $UPDATED_VERSION --arg CHANGE_NOTES "$CHANGE_NOTES" '.[$UPDATED_VERSION].en = $CHANGE_NOTES' resources/.homeychangelog.json.bak > resources/.homeychangelog.json
        rm resources/.homeychangelog.json.bak
        
        git add resources/app.json resources/.homeychangelog.json
        git commit --amend -m "chore(release): $UPDATED_VERSION"
        
        # Update the tag created by [standard-version] to the new commit
        git tag -fa "v$UPDATED_VERSION" -m "chore(release): $UPDATED_VERSION"

        git push --tags origin master

        npm run dist
