name: Build and release master

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'build/.homeychangelog.json'
      - 'build/app.json'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install packages
      run: npm ci && npm run postinstall --if-present
    - name: Transpile with Typescript
      run: npx tsc --build tsconfig.json
    - name: Run tests
      run: npm run test
    - name: Run Homey validation
      run: npx homey app validate -p build -l publish
  
  release:
    needs: build
    name: Create release
    runs-on: ubuntu-latest
    environment:
      name: Publish
    defaults:
      run:
        shell: bash
    env:
      HOMEY_SETTINGS: ${{ secrets.HOMEY_SETTINGS }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Setup credentials
      run: |
        set -e

        mkdir -p $HOME/.athom-cli
        echo "* Created .athom-cli directory"

        which printenv
        env

        echo "* Creating .athom-cli/settings.json..."
        printenv HOMEY_SETTINGS > $HOME/.athom-cli/settings.json
        echo "* Created .athom-cli/settings.json file."
    - name: Install packages
      run: npm ci && npm run postinstall --if-present
    - name: Install parse-changelog
      run: cargo install parse-changelog
    - name: Tag release, bump Homey versioning, push to Github and deploy to Homey App store
      run: |
        set -e

        git config --local user.name "Github Actions"
        git config --local user.email "github-actions@example.com"

        git pull origin master

        npx standard-version

        UPDATED_VERSION=`jq '.version' --raw-output package.json`
        CHANGE_NOTES=$(parse-changelog CHANGELOG.md "$UPDATED_VERSION" || "General improvements")
        
        cat <<< $(jq --arg UPDATED_VERSION $UPDATED_VERSION '.version = $UPDATED_VERSION' build/app.json) > build/app.json
        cat <<< $(jq --arg UPDATED_VERSION $UPDATED_VERSION --arg CHANGE_NOTES $CHANGE_NOTES '.[$UPDATED_VERSION].en = $CHANGE_NOTES' build/.homeychangelog.json) > build/.homeychangelog.json

        git add build/app.json build/.homeychangelog.json
        git commit --amend

        git push --tags origin master

        echo "n" | npm run dist
