name: Pull request

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout
    - uses: actions/setup-node
      with:
        node-version: 16.0
    - name: Install packages
      run: npm ci && npm run postinstall --if-present
    - name: Transpile with Typescript
      run: npx tsc --build tsconfig.json
    - name: Run tests
      run: npm run test
    - name: Run Homey validation
      run: npx homey app validate -p build -l publish
